on: [push, pull_request]
name: Test, build
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: ianwalter/puppeteer@v2.0.0
      - name: Test
        run: |
          npm install
          npm test
        env:
          GITHUB_ACTION: true

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build
        run: |
          npm run build
